# https://docs.docker.com/compose/yml

neo:
  image: kbastani/docker-neo4j

flask:
  image: richburdon/flask-demo 
  ports:
    - "5000:5000"
  links:
    - neo:NEO

nginx:
  build: .
  ports:
    - "8080:80"
  links:
    - flask:FLASK

